version: "3.8"

services:
  proxy:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app_net

  app1:
    image: hashicorp/http-echo
    command: ["-text=Hello from app1"]
    networks:
      - app_net

  app2:
    image: hashicorp/http-echo
    command: ["-text=Hello from app2"]
    networks:
      - app_net

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: techmarket
    ports:
      - "5432:5432"
    networks:
      - persistence_net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - persistence_net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor_net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitor_net

networks:
  app_net:
  persistence_net:
  monitor_net:
