pipeline {
    agent {
        label 'ansible-agent iaac'
    }

    environment {
        TF_DIR = './iac'
        ANSIBLE_INV_DIR = './config/templates'
        ANSIBLE_CONFIG_DIR = './config'
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {
        stage('1. Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('1.5. IaC Static Analysis (Linting & Security)') {
            steps {
                dir("${TF_DIR}") {
                    echo "-> Ejecutando TFLint (Terraform Linter)..."
                    sh 'tflint' 
                    
                    echo "-> Ejecutando Checkov (Escaneo de Seguridad IaC)..."
                    sh 'checkov -d .' 
                }
                dir("${ANSIBLE_CONFIG_DIR}") {
                    echo "-> Ejecutando Ansible-Lint (Linter de Playbooks)..."
                    sh 'ansible-lint playbook.yaml' 
                }
            }
        }

        // PRUEBAS UNITARIAS
        stage('2.5. Ansible Unit Test (Molecule)') {
            steps {
                echo "-> Ejecutando pruebas unitarias de Molecule..."
                dir("${ANSIBLE_CONFIG_DIR}/molecule/frontend_test") {
                   sh 'molecule test' 
                }
            }
        }

        stage('2.7. Terraform Unit Tests (Terratest)') {
            steps {
                dir("${TF_DIR}/test") {
                    echo "-> Preparando y Ejecutando Terratest..."
                    sh 'go mod tidy'
                    sh 'go test -v -parallel 4'
                }
            }
        }

        // DESPLIEGUE DE INFRAESTRUCTURA
        stage('2. Terraform Init & Plan') {
            steps {
                dir("${TF_DIR}") {
                    sh 'terraform init'
                    sh 'terraform plan -out=tfplan'
                }
            }
        }

        stage('3. Terraform Apply') {
            steps {
                dir("${TF_DIR}") {
                    sh 'terraform apply -auto-approve tfplan'
                }
            }
        }

        stage('4. Generate Ansible Inventory') {
            steps {
                dir("${TF_DIR}") {
                    script {
                        def proxy_ip = sh(returnStdout: true, script: 'terraform output -raw proxy_public_ip').trim()
                        def frontend_ip_0 = sh(returnStdout: true, script: 'terraform output -raw frontend_0_public_ip').trim()
                        def frontend_ip_1 = sh(returnStdout: true, script: 'terraform output -raw frontend_1_public_ip').trim()
                        def database_ip = sh(returnStdout: true, script: 'terraform output -raw database_public_ip').trim()
                        def grafana_ip = sh(returnStdout: true, script: 'terraform output -raw grafana_public_ip').trim()

                        def inventory_template = readFile("${ANSIBLE_INV_DIR}/inventory.ini")
                        def final_inventory = inventory_template
                            .replace('IP_PROXY_PLACEHOLDER', proxy_ip)
                            .replace('IP_FRONTEND_0_PLACEHOLDER', frontend_ip_0)
                            .replace('IP_FRONTEND_1_PLACEHOLDER', frontend_ip_1)
                            .replace('IP_DATABASE_PLACEHOLDER', database_ip)
                            .replace('IP_GRAFANA_PLACEHOLDER', grafana_ip)

                        writeFile file: "${ANSIBLE_CONFIG_DIR}/hosts.ini", text: final_inventory
                    }
                }
            }
        }

        stage('5. Ansible Deploy') {
            steps {
                dir("${ANSIBLE_CONFIG_DIR}") {
                    withCredentials([sshUserPrivateKey(credentialsId: 'SMARTRETAIL-IAC-KEY', keyFileVariable: 'SSH_KEY')]) {
                        sh 'ansible-playbook -i hosts.ini playbook.yaml --private-key $SSH_KEY -u ubuntu'
                    }
                }
            }
        }

        // INTEGRACIÓN
        stage('5.5. Integration Test (Proxy Health)') {
            steps {
                script {
                    dir("${TF_DIR}") {
                        def proxy_ip = sh(returnStdout: true, script: 'terraform output -raw proxy_public_ip').trim()
                        echo "Verificando Proxy en: ${proxy_ip}"
                        sh "curl -s -o /dev/null -w '%{http_code}' http://${proxy_ip}:80 | grep 200"
                    }
                }
            }
        }

        //END-TO-END (E2E)
        stage('5.7. End-to-End Test (E2E)') {
            steps {
                script {
                    dir("${TF_DIR}") {
                        def proxy_ip = sh(returnStdout: true, script: 'terraform output -raw proxy_public_ip').trim()
                        dir("..") {
                            sh 'chmod +x e2e_test.sh'
                            sh "./e2e_test.sh ${proxy_ip}"
                        }
                    }
                }
            }
        }

        // REPORTE Y CALIDAD
        stage('5.9. Quality Gate (SonarQube Analysis)') {
            steps {
                echo "-> Iniciando escaneo con SonarQube..."
                sh 'sonar-scanner' 
            }
        }

        stage('6. Destroy Infrastructure (Optional)') {
            steps {
                input message: '¿Desea destruir la infraestructura?', ok: 'Destruir'
                dir("${TF_DIR}") {
                    sh 'terraform destroy -auto-approve'
                }
            }
        }
    }
}
